[tool.ruff]
extend-exclude = [".venv"]
line-length = 88
target-version = "py38"

[tool.ruff.lint]

# Lint rule reference: https://beta.ruff.rs/docs/rules/
select = [
  "B",    # https://pypi.org/project/flake8-bugbear/
  "E",    # https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
  "F",    # https://flake8.pycqa.org/en/latest/user/error-codes.html
  "W",    # https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
  "I",    # https://pycqa.github.io/isort/
  "N",    # https://github.com/PyCQA/pep8-naming
  "ARG",  # https://beta.ruff.rs/docs/rules/#flake8-unused-arguments-arg
  "BLE",  # https://pypi.org/project/flake8-blind-except/
  "C4",   # https://github.com/adamchainz/flake8-comprehensions
  "C90",  # https://pypi.org/project/mccabe/
  "ERA",  # https://pypi.org/project/flake8-eradicate/
  "EXE",  # https://pypi.org/project/flake8-executable/
  "ICN",  # https://pypi.org/project/flake8-import-conventions/
  "ISC",  # https://github.com/flake8-implicit-str-concat/flake8-implicit-str-concat
  "NPY",  # NumPy-specific rules
  "PD",   # https://pypi.org/project/pandas-vet/
  "PERF", # https://pypi.org/project/perflint/
  "PGH",  # https://github.com/pre-commit/pygrep-hooks
  "PIE",  # https://pypi.org/project/flake8-pie/
  "PLC",  # https://beta.ruff.rs/docs/rules/#convention-plc
  "PT",   # https://github.com/m-burst/flake8-pytest-style
  "RET",  # https://pypi.org/project/flake8-return/
  "RUF",  # https://beta.ruff.rs/docs/rules/#ruff-specific-rules-ruf
  "SIM",  # https://pypi.org/project/flake8-simplify/
  "TRY",  # https://pypi.org/project/tryceratops/
]

ignore = ["ISC001", "E501", "W191", "PD901", "TRY003"]

# Errors to fix during make check via --fix
fixable = [
  "I", # Sort imports a la isort.
]

[tool.ruff.per-file-ignores]
"test_*.py" = ["E501"]      # Relax line length requirement in tests.
"config/full.py" = ["E501"] # Relax line length requirement in jobs config.
"__init__.py" = ["F401"]    # Allow unused imports in init files.
"*.py" = ["N812"]           # We normally import spark functions in capital case.

[tool.ruff.isort]
force-sort-within-sections = false
combine-as-imports = true