baseURL = 'https://opc.ulsterworldly.com/'
languageCode = 'en-us'
title = 'Orthodox Presbyterian Church Congregational Registry'
theme = 'nostyleplease'
[taxonomies]
  'minister' ='ministers'
  'state' = 'states'
  'received_from' = 'received_from'
  'withdrawal_to' = 'withdrawal_to'
  'year' = 'year_established'


[outputFormats]
  [outputFormats.SearchIndex]
  baseName = "search"
  mediaType = "application/json"
  isPlainText = true
  notAlternative = true

[outputs]
  home = ["HTML","RSS", "SearchIndex"]
