baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Orthodox Presbyterian Church Congregation Registry'
theme = 'nostyleplease'
[taxonomies]
  'minister' ='ministers'
  'state' = 'states'
  'received_from' = 'received_from'
  'year' = 'year_established'